global:
   scrape_interval: 1s
 
scrape_configs:
  - job_name: "api-server"
    consul_sd_configs:
      - server: 'consul:8500'
        services: [] # Auto discover all services
    relabel_configs:
    - source_labels: [__meta_consul_service]
      regex: ".*api-server.*"
      action: keep